notifications:
  email: false

dist: xenial

language: c
compiler: gcc

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages:
      - autopoint
      - ca-certificates
      - docbook-simple
      - docbook-xsl
      - gettext
      - libdb-dev
      - libgdbm-dev
      - libgnutls-dev
      - libgpgme11-dev
      - libgss-dev
      - libkyotocabinet-dev
      - liblmdb-dev
      - liblua5.2-dev
      - libnotmuch-dev
      - libqdbm-dev
      - libsasl2-dev
      - libslang2-dev
      - libssl-dev
      - libtokyocabinet-dev
      - libxml2-utils
      - lua5.2
      - lynx
      - xsltproc
  coverity_scan:
    project:
      name: "neomutt/neomutt"
      description: "Teaching an Old Dog New Tricks"
    notification_email: rich@flatcap.org
    build_command_prepend: "./configure $OPTS"
    build_command: "make"
    branch_pattern: coverity

git:
  depth: 3

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "akQWaCea8IiHqHL6TWz6nBJF1aqU/u2O4MixUzsxNYckIqJbEo/r3UxIrsMFlL7/rNeI+cGOX9VtFGd9vbi04dFcqRSgQzsBCJ3O10zsfp29+KVGScPOWsIRs0zuqlSMKixCKjdlSWjaZpT+hFFjc9vVJdvZRln8ZqwbaQNTIeCg5QoOjYi5zCaV7IdwUgTfGKy3p/aG2v8uuvNcWL2EZEL3JEerIwOaE9IMF+2y6Z2b+kAU5zgaPF/mPz4yiIV6K7HuP0hdqiUqBJfnCSk7XrMyQVZAzcmlOSRyE6niDdZcvjedCnRR4M67gGgF0818et662YzXpdOOClRuGBeJff5fxnw7uT1xBWXHQ4z4rsgrDzLTHecdrlLAb7ZNaoxLKQyvZSysJ2GZdrzF4W5QluKIPbAuxdeiR5EdU/OTEhBsLmTPGv7L5f+hRTHfD+K/QhIZ/BYKP2pXlJFNEh4uuL5ljenJoAt405dqwzfWckF0j26vcP7+wW/qhpsXN0ToofmoNWPYPD8WD6vpSjk9WgFl1eZNSrTG51VMZKgUw2FsTNys7FhDpLaSJzNvC1PiKVSAxyo3gKP8fHzx0aJY0odyPM4ccLArkTgH2c3NBaHvhtgwFrVdXqoORmSrovF1FIOBqG6FCN1xrqtJ3qHSmU+NulpmODIbInlSrfR4okU="
  matrix:
    - OPTS="--disable-doc --gpgme --lua --notmuch --bdb --with-domain=example.com --gdbm --gnutls --gss --homespool --kyotocabinet --lmdb --mixmaster --qdbm --sasl --tokyocabinet"

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make ; fi

